### PR TITLE
German translation

### LINKED ISSUE #17: Are you interessted in german text translations?
Hi,

we recently started a new game with your mod in our Civ group. We all do play the german version of the game. The changes made have no effect on the german texts, which led to some confusion.

We are happy to contribute a german translation of the changes (and keep them up to date) if you add them to the mod.

Thanks for the awesome work.

### PR DESCRIPTION
**Pull request by masseelch**
Fixes #17.

How do we provide translations for future changes?

### CODE REVIEW

**Comment by codenaugh** [comment]
Are you on discord? I have a discord group convo with all the translators.

**Comment by masseelch** [comment]
I have a discord account but very rarely log into it. Just send me the link and I'll join. I think I still get an email, if a new message appears in the conversation.

**Comment by codenaugh** [comment]
ok, we would need to be on the same server or be friends in order to communicate, so just join discord.gg/cpl and then send @codenaugh a friend request. Once we are friends you can leave that server if you want.

**Comment by masseelch** [comment]
I sent a request (from kannil).

Changes are ready to be merged. Started a game yesterday. German language is correctly displayed pre-game and in-game.

**Pull request merged**
