### PR TITLE
Only apply certain modifiers if base type exists

### PR DESCRIPTION
**Pull request by cjcjameson**
Resolves issues with loading as reported:
https://steamcommunity.com/sharedfiles/filedetails/?id=1368312893

Addresses error messages in logs during

`[2385902.440] [Gameplay]: Validating Foreign Key Constraints...`

### CODE REVIEW

**Comment by cjcjameson** [comment]
@clanier9 I refactored the sql to guard against non-existent base-types. I don't know if I addressed everything comprehensively, but this seems to be enough to fix things to get it to boot for me...

I have mods: BBS, BBG, CQUI, R&F

**Comment by cjcjameson** [comment]
Something I'm not clear on is: "what dialect of SQL is Civ 6 using?"

I see this error message in my database.log:

[2386553.440] [Gameplay] ERROR: near "IF": syntax error

Which suggests that things start working simply because the whole file stops parsing at that point

**Comment by cjcjameson** [comment]
Full error message:

```
[2433480.440] [Gameplay] ERROR: FOREIGN KEY constraint failed
[2433480.440] [Gameplay] ERROR: FOREIGN KEY constraint failed
[2433480.440] [Gameplay]: Validating Foreign Key Constraints...
[2433480.440] [Gameplay] ERROR: Invalid Reference on BuildingModifiers.BuildingType - "BUILDING_PRASAT" does not exist in Buildings
[2433480.440] [Gameplay] ERROR: Invalid Reference on Improvement_ValidTerrains.ImprovementType - "IMPROVEMENT_PYRAMID" does not exist in Improvements
[2433480.440] [Gameplay] ERROR: Invalid Reference on TraitModifiers.TraitType - "TRAIT_LEADER_MONASTERIES_KING" does not exist in Traits
[2433480.440] [Gameplay] ERROR: Invalid Reference on TraitModifiers.TraitType - "TRAIT_CIVILIZATION_KHMER_BARAYS" does not exist in Traits
[2433480.440] [Gameplay] ERROR: Invalid Reference on TraitModifiers.TraitType - "TRAIT_CIVILIZATION_KHMER_BARAYS" does not exist in Traits
[2433480.440] [Gameplay] ERROR: Invalid Reference on TraitModifiers.TraitType - "TRAIT_CIVILIZATION_KHMER_BARAYS" does not exist in Traits
[2433480.440] [Gameplay] ERROR: Invalid Reference on TraitModifiers.TraitType - "TRAIT_LEADER_LITHUANIAN_UNION" does not exist in Traits
[2433480.440] [Gameplay] ERROR: Invalid Reference on TraitModifiers.TraitType - "TRAIT_LEADER_LITHUANIAN_UNION" does not exist in Traits
[2433480.440] [Gameplay] ERROR: Invalid Reference on UnitReplaces.CivUniqueUnitType - "UNIT_KHMER_DOMREY" does not exist in Units
[2433480.440] [Gameplay]: Failed Validation.
```

**Comment by cjcjameson** [comment]
Not working yet

**Comment by cjcjameson** [comment]
Sounds like @clanier9 has an approach to use PRAGMA

**Comment by codenaugh** [comment]
Change pushed. Please let me know if it's fixed for you.

**Pull request closed without merging**
